# Generated by Django 5.0.6 on 2026-06-11 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCorpusEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('organization', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Policy corpus entries',
                'ordering': ['organization', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Document Upload'), ('index', 'Document Indexed'), ('audit', 'Compliance Audit Run'), ('report_download', 'Report Downloaded'), ('delete', 'Document Deleted'), ('login', 'User Login')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('error', 'Error')], default='pending', max_length=20)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('chroma_doc_id', models.CharField(blank=True, max_length=255)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('compliance_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('violations_json', models.JSONField(default=list)),
                ('citations_json', models.JSONField(default=list)),
                ('retrieved_chunks_json', models.JSONField(default=list)),
                ('cot_reasoning', models.TextField(blank=True)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('top_k_retrieved', models.PositiveSmallIntegerField(default=20)),
                ('top_k_reranked', models.PositiveSmallIntegerField(default=8)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regulation_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('risk', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('evidence', models.TextField()),
                ('citation', models.TextField()),
                ('corrective_action', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.compliancereport')),
            ],
            options={
                'ordering': ['report', 'risk'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='core_docume_status_daedd3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='core_docume_created_f1aada_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='core_docume_uploade_8c924b_idx'),
        ),
    ]
